version: '3.8'

services:
  zap:
    container_name: zap_container
    build: .
    ports:
    - "127.0.0.1:4000:4000"
    volumes:
    - zap:/src
    command: "node index.js"
  db:
    container_name: postgres
    image: postgres
    ports: 
    - "5432:5432"
    volumes: 
    - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: loja
    
volumes:
  pgdata:
  zap: